### ISSUE TITLE
bug: @next version is tagged incorrectly?

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/helia-verified-fetch#66]
<img width="808" alt="image" src="https://github.com/ipfs/helia-verified-fetch/assets/1173416/aade53c3-53dc-4a85-a834-73cd37c275e3">

`@next` version should be 1.3.13 or similar

**Comment by achingbrain** [comment]
Since https://github.com/ipfs/helia-verified-fetch/tree/fdc83b8869066a961ae346f153e4b6b486091f01 this module publishes a new version on every commit, it doesn't use `@next` tags.  The tag in question is from before the repo switched over to using the [js-test-and-release](https://github.com/ipfs/helia-verified-fetch/blob/main/.github/workflows/js-test-and-release.yml) workflow.

If you want pre-release tags you need to switch to using release-please-action - eg: https://github.com/ipfs/helia/blob/main/.github/workflows/main.yml#L167-L217
